#!/bin/bash

if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

files=(
    $HOME/.dotfiles/shell/bash_options
    $HOME/.dotfiles/shell/bash_exports
    $HOME/.dotfiles/shell/bash_aliases
    $HOME/.dotfiles/shell/functions
    $HOME/.dotfiles/shell/bash_prompt
    $HOME/.bash_profile.local 
)
for index in ${files[@]}
do
    if [[ -r ${index} ]]; then
        source ${index}
    fi
done
unset files

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export NVM_DIR="/home/smialy/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

[ -s "/usr/local/bin/virtualenvwrapper.sh" ] && . "/usr/local/bin/virtualenvwrapper.sh"
