#!/bin/bash

export EDITOR="vim"

# Ignore duplicate
export HISTCONTROL=ignoredups

# Increase the maximum number of lines contained in the history file
export HISTSIZE=10000
export HISTFILESIZE=100000
export HISTIGNORE="cd:cd -:pwd;exit:date"

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history
export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

export WORKON_HOME="${HOME}/.pyenvs"
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS=""
