#!/bin/bash

run_node(){
    
    #install nvm
    if ! app_exists 'nvm'; then
        curl -fSLs https://raw.githubusercontent.com/creationix/nvm/v0.24.1/install.sh | bash
        echo "nvm"
    fi
}
