#!/bin/bash

if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

for file in ~/.dotfiles/bash/dots/*; do
    if [[ -r ${file} ]]; then
        source ${file}
    fi
done
unset file;

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
[ -s "$HOME/.local/bin/virtualenvwrapper.sh" ] && source "$HOME/.local/bin/virtualenvwrapper.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PYENV_ROOT="$HOME/.pyenv"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export PATH="/home/smialy/.local/bin:$PYENV_ROOT/bin:$PATH"

export NODE_OPTIONS=--max-old-space-size=8192

[ -s "$HOME/.bash_local" ] && source "$HOME/.bash_local"